//! The art packs. Each module renders a fixed number of coherent images from a fixed
//! seed, returning an [`Art`] with its clock slot.

use crate::Art;

pub mod botanica;
pub mod cities;
pub mod constellations;
pub mod deco;
pub mod maze;
pub mod moons;
pub mod mountains;
pub mod tides;
pub mod typographic;
pub mod woodcut;

/// A pack: metadata plus its renderer.
#[derive(Clone, Copy)]
pub struct Pack {
    /// Directory name and id.
    pub id: &'static str,
    /// Display name.
    pub name: &'static str,
    /// One-line description.
    pub description: &'static str,
    /// Number of images.
    pub count: usize,
    /// Render image `i` (0-based).
    pub render: fn(usize) -> Art,
}

/// Images per pack.
pub const PER_PACK: usize = 5;

/// Every pack, in display order.
pub fn all() -> Vec<Pack> {
    vec![
        mountains::PACK,
        tides::PACK,
        constellations::PACK,
        botanica::PACK,
        deco::PACK,
        typographic::PACK,
        cities::PACK,
        moons::PACK,
        maze::PACK,
        woodcut::PACK,
    ]
}

/// Look a pack up by id.
pub fn find(id: &str) -> Option<Pack> {
    all().into_iter().find(|p| p.id == id)
}

/// The generator's credit line.
pub const CREDIT: &str = "Generated by quire-sleep; CC0 1.0";
